### PR TITLE
Extend VehicleObject with property isOnGround.

### PR DESCRIPTION
**Pull request by poirierlouis**
Depends on https://github.com/WopsS/RED4ext.SDK/pull/142.

### CODE REVIEW

**Comment by psiberx** [comment]
I think RTTI registration is missing?

**Comment by poirierlouis** [comment]
Oh right!

**Comment by psiberx** [comment]
And you have to include it in `rtti.cpp` to compile.

**Comment by poirierlouis** [comment]
Sorry, done :)

**Pull request merged**
